// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjxlkyopfborhrxqvkws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqeGxreW9wZmJvcmhyeHF2a3dzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDIyNTEsImV4cCI6MjA2OTM3ODI1MX0.IYWohXpuYooLPE5XgFp8s0dZmb2rIffFq1UmMQKvc8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});